name: Build Asset for Release
on: 
  release:
    types: [published]

jobs:
  build:
    
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Update zip
        run: |
          cd pcm
          python build.py
          cd build
          echo "ZIP_NAME_WITH=$(ls SparkFun-KiCad-Libraries*-with-pcm.zip)" >> $GITHUB_ENV
          echo "PCM_NAME_WITH=$(ls SparkFun-KiCad-Libraries*-with-pcm.zip | rev | cut -c 5- | rev)" >> $GITHUB_ENV
          echo "ZIP_NAME_WITHOUT=$(ls SparkFun-KiCad-Libraries*-without-pcm.zip)" >> $GITHUB_ENV
          echo "PCM_NAME_WITHOUT=$(ls SparkFun-KiCad-Libraries*-without-pcm.zip | rev | cut -c 5- | rev)" >> $GITHUB_ENV

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./pcm/build/${{ env.ZIP_NAME_WITH }}
            ./pcm/build/${{ env.ZIP_NAME_WITHOUT }}
